name: Fetch kev
on:
  schedule:
    - cron: '0 0/12 * * *'
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: page
      
      - name: Fetch known_exploited_vulnerabilities file
        run: wget https://www.cisa.gov/sites/default/files/feeds/known_exploited_vulnerabilities.json -O kev.json
      
      - name: Commit known_exploited_vulnerabilities
        run: |
          git config --global user.name 'Marcuccio'
          git config --global user.email 'marcuccio.dev@gmail.com'
          (git add kev.json && git commit -m "fetch kev" && git push) || exit 0