name: Fetch inthewild
on:
  schedule:
    - cron: '0 0/12 * * *'
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: page
      - name: Fetch in_the_wild file
        run: wget https://inthewild.io/api/exploited -O itw.json
      - name: Commit in_the_wild
        run: |
          git config --global user.name 'Marcuccio'
          git config --global user.email 'marcuccio.dev@gmail.com'
          (git add itw.json && git commit -m "fetch inthewild" && git push) || exit 0