name: Fetch CVE from nuclei@projectdiscovery
on:
  schedule:
    - cron: '0 0/12 * * *'
    
    
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: page
          
      - name: setup-yq
        uses: chrisdickinson/setup-yq@v1.0.0

      - name: fetch nuclei_cves
        run: |
          wget https://github.com/projectdiscovery/nuclei-templates/archive/main.zip
          unzip main.zip nuclei-templates-main/http/cves/*
          find "./nuclei-templates-main/http/cves/" -type f -name "*.yaml" -exec basename {} \; > nuclei.txt
          sed -i 's/.yaml//g' "nuclei.txt"

      - name: commit & push
        run: |
          git config --global user.name 'Marcuccio'
          git config --global user.email 'marcuccio.dev@gmail.com'
          git add nuclei.txt && git commit -m "fetch of nuclei_cves" && git push
