name: Fetch known CVE from nuclei@projectdiscovery
on:
  schedule:
    - cron: '0 0 0 ? * * *'
    
    
jobs:
  pull-and-commit:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: page
      - run: |
          git clone https://github.com/projectdiscovery/nuclei-templates.git
          find "./nuclei-templates" -type f -name "*.yaml" > cve-files.txt
          sed -i 's/.yaml//g' "cve-files.txt"
          git add cve-files.txt
          git commit -m "Upadate list of testable CVEs with nuclei"
